name: ten.java.theme2
main: net.cubespace.tenjava.TenJavaPlugin
description: Secret things and stuff
version: 0.1.0
commands:
    fight:
        description: Send an invitation to another Player
        usage: "Usage: /fight"
        permission: efight.command.fight
        permission-message: You can't fight other People.