name: ten.java.theme2
main: net.cubespace.tenjava.TenJavaPlugin
description: Secret things and stuff
version: 0.1.0
commands:
    setuparea:
        description: Setup a new Area
        usage: "Usage: /setuparea"
        permission: efight.command.setuparea
        permission-message: You can't setup Areas.